EMAIL = "admin@email.com"
GMAIL_APP_PASSWORD = "gmail_password"
EMAIL_RECIPIENTS = "user1@email.com, user2@email.com"


[connections.meal_plan_db]
url = "sqlite:///meal_plan.db"

[connections.shopping_list_db]
url = "sqlite:///shopping_list.db"

